apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-aws-account-sa
  namespace: test-pods

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-aws-account-role
  namespace: test-pods
rules:
  - apiGroups: ["boskos.k8s.io"]
    resources:
      - resources
    verbs:
      - get
      - list      
      - create
      - patch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-aws-account-rolebinding
  namespace: test-pods
subjects:
  - kind: ServiceAccount
    name: patch-aws-account-sa
roleRef:
  kind: Role
  name: patch-aws-account-role
  apiGroup: rbac.authorization.k8s.io
