dashboard_groups:
- name: vagator
  dashboard_names:
    - test-prow
    - build-images

dashboards:
- name: test-prow
  dashboard_tab:
    - name: Vagator Testing Prow
      test_group_name: test-prow-group
- name: build-images
  dashboard_tab:
    - name: Vagator Building test images
      test_group_name: build-images-group
    - name: vagator-periodics
      test_group_name: periodic-building-test-images-group
    - name: image-builder
      test_group_name: push-image-builder

test_groups:
- name: test-prow-group
  gcs_prefix: vagator-prow/logs/test-postsubmit
- name: build-images-group
  gcs_prefix: vagator-prow/logs/build-test-image
- name: periodic-building-test-images-group
  gcs_prefix: vagator-prow/logs/periodic-build-test-image
- name: push-image-builder
  gcs_prefix: vagator-prow/logs/push-image-builder
  
