# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-cleaner
  labels:
    app: boskos-cleaner
  namespace: test-pods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boskos-cleaner
  template:
    metadata:
      labels:
        app: boskos-cleaner
    spec:
      serviceAccountName: boskos-cleaner
      terminationGracePeriodSeconds: 300
      containers:
        - name: boskos-cleaner
          image: gcr.io/k8s-staging-boskos/cleaner:v20211015-2401f5c
          args:
            - --boskos-url=http://boskos.test-pods.svc.cluster.local.
            - --namespace=$(NAMESPACE)
            - --use-v2-implementation
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: boskos-cleaner
  namespace: test-pods
---
# Give the cleaner access to update Boskos resources directly
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boskos-cleaner-crd-updater
  namespace: test-pods
subjects:
  - kind: ServiceAccount
    name: boskos-cleaner
    namespace: test-pods
roleRef:
  kind: Role
  name: boskos-crd-updater
  apiGroup: rbac.authorization.k8s.io
---
# Give the cleaner access to its leaderlock
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: boskos-cleaner-leaderlock
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - boskos-cleaner-leaderlock
    verbs:
      - get
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boskos-cleaner-leaderlock
  namespace: test-pods
subjects:
  - kind: ServiceAccount
    name: boskos-cleaner
    namespace: test-pods
roleRef:
  kind: Role
  name: boskos-cleaner-leaderlock
  apiGroup: rbac.authorization.k8s.io
