kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boskos-server
  namespace: test-pods
rules:
  - apiGroups: ["boskos.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
    - update
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    resourceNames:
    - boskos-server
    verbs:
    - get
    - update
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boskos-server
  namespace: test-pods
subjects:
  - kind: ServiceAccount
    name: boskos
    namespace: test-pods
roleRef:
  kind: Role
  name: boskos-server
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boskos-crd-reader
  namespace: test-pods
rules:
  - apiGroups: ["boskos.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boskos-crd-updater
  namespace: test-pods
rules:
  - apiGroups: ["boskos.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "update"]
